### ISSUE TITLE
restore `apipie-rails` gem to stable release

### ISSUE THREAD

**Issue by markmoser** [PinsterTeam/PinsterBase#16]
There is an issue in the `apipie-rails` gem that prevents us from disabling localization. We are using a fork (https://github.com/PinsterTeam/PinsterBase/commit/f3bb598399c4c0f934427a9cc94d6f8d6381df22) until the fix is merged in.

Once `apipie-rails` merge the PR, or provides a better solution update the Gemfile to point back to stable releases of the gem.

You can track the issue and PR here:
* https://github.com/Apipie/apipie-rails/pull/562
* https://github.com/Apipie/apipie-rails/issues/549

**Comment by markmoser** [comment]
PR merged, waiting for version bump and gem release

**Comment by scytherswings** [comment]
Awesome!
