### ISSUE TITLE
sorcery creates users in a way that does not call validations

### ISSUE THREAD

**Issue by markmoser** [PinsterTeam/PinsterBase#17]
Sorcery creates users in a way that does not call validations preventing `set_uuid` to be automatically called. The next gem version will include `build_user` which will allow us to create users and call validations. The PR has merged (https://github.com/Sorcery/sorcery/pull/54) but we have to wait for the version bump or configure the Gemfile to pull from master.

Once the gem is updated the `auth_and_login` method should be revisited.

Related code bits:
* https://github.com/PinsterTeam/PinsterBase/blob/develop/test/models/user_test.rb#L6
* https://github.com/PinsterTeam/PinsterBase/blob/develop/app/models/user.rb#L39
* https://github.com/PinsterTeam/PinsterBase/blob/develop/app/controllers/oauths_controller.rb#L25

**Comment by scytherswings** [comment]
I believe this issue has been resolved
